# Lightweight Enhanced Configuration
# Safe improvements without system crash risk
experiment_name: "lightweight_enhanced_dqn"
description: "Lightweight enhanced DQN with memory optimization and safe improvements"
tags: ["dqn", "lightweight", "enhanced", "stable"]
device: "auto"

agent:
  # Basic hyperparameters
  learning_rate: 0.0001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 0.995
  
  # Training parameters
  batch_size: 32
  memory_size: 10000
  target_update_freq: 1000
  tau: 0.005
  
  # Enhanced features (lightweight)
  use_dueling: false
  use_double_dqn: true
  gradient_clip: 1.0
  use_prioritized_replay: false
  
  # Agent type
  agent_type: "lightweight_enhanced"

environment:
  # CARLA connection
  carla_host: "localhost"
  carla_port: 2000
  town: "Town03"
  
  # Simulation parameters
  timestep: 0.05
  time_scale: 1.0
  max_episode_steps: 1000
  
  # Sensor configuration
  enable_sensors: ["rgb_camera", "gnss", "imu"]
  image_size: [84, 84]
  
  # Visualization
  enable_pygame_display: false
  pygame_width: 1280
  pygame_height: 720
  disable_sensor_views: true
  
  # Data saving
  save_sensor_data: false
  sensor_data_save_path: "./data/sensor_data"
  sensor_save_interval: 100

training:
  # Episode parameters
  num_episodes: 1000
  max_steps_per_episode: 1000
  
  # Evaluation
  eval_interval: 25
  num_eval_episodes: 5
  epsilon_eval: 0.0
  
  # Saving and logging
  save_interval: 100
  save_dir: "./models"
  log_level: "INFO"
  load_model_from: null
  
  # Performance optimization
  optimization_mode: "balanced"
  enable_performance_monitoring: true
  enable_observation_preprocessing: true

preprocessing:
  enable_compression: true
  primary_camera_size: [64, 64]
  secondary_camera_size: [32, 32]
  use_grayscale_secondary: true
  normalize_sensors: true
  enable_caching: true
  cache_size: 100

monitoring:
  enable_plots: true
  save_interval: 100
  plot_update_interval: 5
  metrics_window_size: 100
  log_dir: "./logs/monitoring"
  
  # Real-time dashboard
  enable_dashboard: false
  dashboard_port: 8080 